version: "2"
services:
  server:
    image: diego10rocha/pbl1_redes:servidor_atendimento_bridge
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /app
    ports:
      - "1017:1017/tcp"
    network_mode: "bridge"