version: "2"
services:
  server:
    stdin_open: true
    tty: true
    image: diego10rocha/pbl1_redes:medidor_energia_1017_final
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /app